# MeshCore SMS Gateway Services
send_sms:
  name: Send SMS Message
  description: Send an SMS message through the MeshCore SMS gateway
  fields:
    phone_number:
      name: Phone Number
      description: The phone number to send the SMS to (include country code, e.g., +1234567890)
      required: true
      example: "+1234567890"
      selector:
        text:
    message:
      name: Message
      description: The SMS message to send
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
          multiline: true
    entry_id:
      name: Gateway Entry ID
      description: Specific gateway to use (optional, uses first available if not specified)
      required: false
      example: "abc123def456"
      selector:
        text:

test_meshcore:
  name: Test MeshCore Message
  description: Test sending a message to MeshCore
  fields:
    recipient:
      name: Recipient
      description: MeshCore recipient (node name or 'all' for broadcast)
      required: true
      example: "nodename"
      selector:
        text:
    message:
      name: Message
      description: Message to send
      required: true
      example: "Test message"
      selector:
        text:

get_webhook_info:
  name: Get Webhook Info
  description: Get the Twilio webhook URL and setup instructions
  fields: {}