# MeshCore SMS Gateway Services

send_sms:
  name: Send SMS
  description: Send an SMS message through the gateway
  fields:
    phone_number:
      name: Phone Number
      description: Recipient phone number with country code
      required: true
      example: "+1234567890"
      selector:
        text:
    message:
      name: Message
      description: SMS message content
      required: true
      example: "Hello from Home Assistant"
      selector:
        text:
          multiline: true

test_meshcore:
  name: Test MeshCore Message
  description: Test sending a message to MeshCore
  fields:
    recipient:
      name: Recipient
      description: MeshCore recipient (node name or 'all' for broadcast)
      required: true
      example: "nodename"
      selector:
        text:
    message:
      name: Message
      description: Message to send
      required: true
      example: "Test message"
      selector:
        text:

get_webhook_info:
  name: Get Webhook Info
  description: Get the Twilio webhook URL and setup instructions
  fields: {}